#!/bin/bash

export DOCKER_BUILDKIT=1
export BUILDKIT_PROGRESS=plain

if [[ "x${DOCKER_TAG}" == "x5" ]]; then
    mysql_version=5
else
    mysql_version=8
fi

echo "Launching build with mysql version ${mysql_version}"

docker build \
    --build-arg MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-test}" \
    --build-arg mysql_version="${mysql_version}" \
    --build-arg mysql_apt_config_version="${mysql_apt_config_version:-0.8.12-1_all}" \
    --build-arg download_dir="${download_dir:-/tmp/}" \
    --build-arg download_base_url="${download_base_url:-https://dev.mysql.com/get/}" \
    -f "${DOCKERFILE_PATH}" \
    -t "${IMAGE_NAME}" .